### ISSUE TITLE
Turn `ParseError` into a real error

### ISSUE THREAD

**Issue by laralove143** [chronotope/chrono-tz#121]
Currently it's just a `String`, this is unidiomatic for various reasons:
- It doesn't implement `std::error::Error`, meaning `?` or any kind of error coercion isn't possible (i.e with anyhow)
- It doesn't give enough info on what the error is going to be, the documentation could give this info but that's not ideal
- It's an unexpected API
- It might be unnecessary allocation (converting an error to string isn't always necessary)
- It doesn't allow polymorphism or fields

**Comment by djc** [comment]
Sounds reasonable, I'd be happy to review a PR in this direction!
