### ISSUE TITLE
Case insensitive timezone matching

### ISSUE THREAD

**Issue by IanWorthington** [chronotope/chrono-tz#125]
I read a timezone from the command line into `str` and parse it using:

`
let ps: Result<Tz, String> = str.parse();
`

This works fine when I specify the timezone as CET or Europe/Paris, for example, but fails if I don't match the case correctly.

This is slightly irritating from a user's perspective.  Is there any way to perform a case insensitive matching?

**Comment by esheppa** [comment]
Thanks @IanWorthington

We are using the `phf` library to [store](https://github.com/chronotope/chrono-tz/blob/b1104001236cecc51123f857d91519f2afc2b08e/chrono-tz/src/timezones.rs.example#L16) the tzdb data in the library, so this may not be trivial as we need to ensure that it works both with the correct casing and other casing, but we can only store one version as the key

One thing for us to consider is that using the `to_lowercase` functions allocates, which may not be ideal from a performance perspective, but we could investigate using [`make_ascii_lowercase`](https://doc.rust-lang.org/std/primitive.str.html#method.make_ascii_lowercase) to resolve this.

If you have time we would greatly appreciate a PR to resolve this

**Comment by IanWorthington** [comment]
Thanks for your response @esheppa.

I am very much a neophyte Rust programmer, but I'm happy to take a look.

The first thing that occurs to me though is to ask if you /really/ would want to fail a lookup simply on a case mismatch?  Are there (or could there ever be) entries that differ only by case?

**Comment by djc** [comment]
Note that we do have a `case-insensitive` Cargo feature, so it looks like there are some facilities for case-insensitive timezone matching. Among other things, this passes an `uncased` feature flag to phf, so something is happening there. I couldn't quite figure out how this is exposed as part of the chrono-tz API, though.

**Comment by djc** [comment]
Yes, it looks like you have to use `chrono_tz::from_str_insensitive()`. Unfortunately because this API is added by the build script depending on the Cargo features, it doesn't make it into the crate docs on docs.rs...

If you have any suggestions for how to improve the documentation around this, please submit a PR.

**Comment by Imberflur** [comment]
It looks like the documentation on docs.rs was improved in https://github.com/chronotope/chrono-tz/commit/af124220bf788b031171b881809d691fa48fee68
