### ISSUE TITLE
Use of arbitraries feature

### ISSUE THREAD

**Issue by arnodb** [chronotope/chrono-tz#132]
Hi,

I see that the derive of `Arbitrary` has been added a few months ago in `chrono-tz-build` and I would very much like to use it. However I think it cannot be "used" until the build module is released. Officially it is still at 0.1.0.

Would it be possible to release a new version of `chrono-tz-build` or is there anything blocking it?

Thanks in advance,

Arnaud

**Comment by djc** [comment]
I've just published chrono-tz-build 0.2.0, hope that helps.

**Comment by arnodb** [comment]
Thanks, it looks to be working as expected :100: .
