### ISSUE TITLE
Is UTC stripped out too? Should we update the Readme?

### ISSUE THREAD

**Issue by frederikhors** [chronotope/chrono-tz#148]
I'm using the env var `$env:CHRONO_TZ_TIMEZONE_FILTER='(Europe/Berlin)'` and building with `cargo build`, then I get this error:

```
Compiling chrono-tz v0.8.6
error[E0599]: no variant or associated item named `UTC` found for enum `Tz` in the current scope
  --> C:\Users\Fred\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chrono-tz-0.8.6\src\timezone_impl.rs:14:13
   |
14 |         Tz::UTC
   |             ^^^ variant or associated item not found in `Tz`
   |
  ::: C:\prj\target\release\build\chrono-tz-5b053da3462d6436\out/timezones.rs:13:1
   |
13 | pub enum Tz {
   | ----------- variant or associated item `UTC` not found for this enum

For more information about this error, try `rustc --explain E0599`.
error: could not compile `chrono-tz` (lib) due to 1 previous error
```

Why?

Is UTC stripped out too? Should we update the Readme?

**Comment by djc** [comment]
Yeah, I would expect that UTC gets stripped out too if you do that. Why do we need to update the README for that?

**Comment by frederikhors** [comment]
@djc my bad. I think we should reopen this.

What I'm noticing here is that in the regex it is necessary to have `UTC` too even if I don't use it in my code.

**Comment by djc** [comment]
I'm open to that, but I won't be able to dig into it myself. Happy to review a PR, though!

**Comment by frederikhors** [comment]
I'll try in a few days...
