### ISSUE TITLE
impl Default for Tz must be declared public

### ISSUE THREAD

**Issue by rxdiscovery** [chronotope/chrono-tz#150]
Hello,

I have a small remark :

```rust
impl Default for Tz {
    fn default() -> Self {
       Tz::UTC
    }
}
```

must be declared public, "pub impl"

**Comment by djc** [comment]
Pretty sure `impl`s don't have associated privacy, and you didn't explain why you want this.

**Comment by rxdiscovery** [comment]
@djc  you're absolutely right, sorry it was a bug with my ide and rust-analyzer :+1:
