### ISSUE TITLE
chrono-tz release notes feedback

### ISSUE THREAD

**Issue by robsdedude** [chronotope/chrono-tz#178]
Hi and thanks for the nice crate.

I use it as a dependency on one my libraries and was getting ready to bump chrono-tz from `0.8` to `0.9`. While doing so, I noticed that this experience is less smooth than with other crates. For two reasons:

 1. It's harder to find what has changed at all: `CHANGELOG.md` isn't up to date and the release page is pretty noisy with listing ️`parse-zoneinfo` releases as well
 2. The [release notes for 0.9.0](https://github.com/chronotope/chrono-tz/releases/tag/v0.9.0) could be more explicit about what changes are actually breaking changes.

Just figured I leave some feedback on my experience. Feel free to close the issue once you've read it =)

**Comment by robsdedude** [comment]
> Can you say a bit more about the problem you hit?

I think I wrote most feedback I had. To summarize: I was bumping the dependency and wanted to check what breaking changes were introduced so that I know if I had to apply any changes to my code. This felt a bit more cumbersome than with other crates, e.g., `rustls`, which I just use as some random example here because I also was bumping that).

> Yesterday we moved `parse-zoneinfo` into this repo and are still integrating it.

:D it might well be that the releases were only so noisy because of that on-off thing then.

I think the only point that remains that you might want to consider: you could clearly mark what changes in a release constitute the breaking ones. Either by using some marker (e.g., an emoji) or by putting them together under one headline.

**Comment by pitdicker** [comment]
Thank you for the feedback :+1:.
The [latest release notes](https://github.com/chronotope/chrono-tz/releases/tag/v0.9.0) had a 'Changed' section but indeed didn't call out the breaking change.
