### ISSUE TITLE
Question : Why It returned the wrong timezone in the format

### ISSUE THREAD

**Issue by SudoDios** [chronotope/chrono-tz#184]
Hi.
i create datetime<tz> like :
```rust
Tz::Iran.timestamp_millis_opt(959933366136).unwrap()
```
But when I print the formatted date, it says the time zone is wrong  : 
```rust
println!("{}",date.format("%Y-%m-%d %H:%M:%S %:z"))
// output : 2000-06-02 12:39:26 +04:30
```
while it should be +03:30

**Comment by djc** [comment]
Why do you think it should be 03:30?

**Comment by SudoDios** [comment]
Because Iran timezone is 03:30

**Comment by SudoDios** [comment]
Is this because of day night?

**Comment by djc** [comment]
As you can see in for example https://en.wikipedia.org/wiki/Iran_Standard_Time, in 2000 Iran still observed daylight savings time.

**Comment by SudoDios** [comment]
Ok thanks 🙏
