### ISSUE TITLE
Is This Project Still Alive?

### ISSUE THREAD

**Issue by mhseiden** [chronotope/chrono-tz#19]
We've been on a forked branch for quite a while, and my colleague opened this PR months ago. https://github.com/chronotope/chrono-tz/pull/14 

If y'all are lacking maintainers for this particular repo, we're happy to sign on and help. We rely on this internally, and would prefer not to continue forking if we find issues or reasonable improvements. 

Thanks!

**Comment by quodlibetor** [comment]
OMG I didn't realize that I didn't have github notifications turned on for this repo (I only got membership recently).

While that doesn't provide a lot of assurance, I have now turned on notifications and will be monitoring it more closely :-(

**Comment by quodlibetor** [comment]
I am excited to get more members contributing so that I'm not the only person maintaining it. If you're looking for work to do one of the highest priority and easiest-to-achieve things would be just creating a travis config, if you're interested in doing that I'll enable travis for this repo.

**Comment by quodlibetor** [comment]
I'm going to close this because the project _is_ still alive, but contribution of any sort is very much welcome, feel free to drop into https://gitter.im/chrono-rs/Lobby if you want to talk about anything.

**Comment by quodlibetor** [comment]
Ehhhhh I don't actually have publish permissions on this repo, @djzin if you want to `cargo owner --add github:chronotope:release-manager` I'll help keep this updated.
