### ISSUE TITLE
Exposing `TzOffset` in the public API?

### ISSUE THREAD

**Issue by bspeice** [chronotope/chrono-tz#35]
Ran into an issue in bspeice/dtparse#18 where I can't retrieve a `FixedOffset` even after parsing a `Tz` because `TzOffset` isn't exported in the public API (despite itself being marked public). Is there a better way for me to build a `FixedOffset` struct given a `Tz`? Or should I refactor my methods to take `impl Timezone` or similar?

**Comment by bspeice** [comment]
Turns out there's not a good way of getting the `FixedOffset` immediately from `Tz`. However, it's not too hard given a reference date:

```rust
fn parse_tz(tzname: &str, ref_date: &NaiveDateTime) -> Option<FixedOffset> {
    let tz: Tz = tzname.parse().ok()?;

    // This is of type `chrono::LocalResult<chrono_tz::TzOffset>`, but because `TzOffset`
    // isn't part of the public API, we can't name the type.
    let offset = tz.offset_from_local_datetime(ref_date);

    // Using `single()` means we only handle the easy case - assume that we're not near a DST transition
    offset.single().map(|o| o.fix())
}
```

**Comment by Kungitoo** [comment]
Could we please revisit opening this type to public? If we can access it with public methods, shouldn't it then also be public?
