### ISSUE TITLE
Abbreviated time zones

### ISSUE THREAD

**Issue by NilsIrl** [chronotope/chrono-tz#44]
Support abbreviated time zones. e.g. `BST`, `IST`

**Comment by workingjubilee** [comment]
This isn't possible without an unambiguous mapping.

**Comment by quodlibetor** [comment]
Partially related to some of the use cases expressed in #54 , I think?

**Comment by pitdicker** [comment]
So creating a timezone from just an abbreviation is impossible, as mentioned before. Getting the abbreviation from a `TzOffset` is possible with the `OffsetName` trait.
