### ISSUE TITLE
PST timezone?

### ISSUE THREAD

**Issue by leshow** [chronotope/chrono-tz#46]
We're deserializing some data and encountered the `PST` timezone, which it doesn't appear that `chrono-tz` has, although it has `EST`. Does it still need to be added?

**Comment by quodlibetor** [comment]
This should depend only on your local timezone database, chrono-tz is mostly a tzdb parser, not a database of timezones.

**Comment by leshow** [comment]
Did some more investigation after, I believe I filed this in error, thank you.
