### ISSUE TITLE
Update to 2020f

### ISSUE THREAD

**Issue by sunng87** [chronotope/chrono-tz#76]
2020f is the latest release from IANA

**Comment by sunng87** [comment]
It seems we have a github action for this but the job was broken.

**Comment by neoeinstein** [comment]
Created #79 to help fix that.

**Comment by AlyoshaVasilieva** [comment]
Is there any update on this? chrono-tz is now 4 versions behind latest

**Comment by quodlibetor** [comment]
0.6.0 has 2021a.
