### ISSUE TITLE
Move to the chronotope organisation?

### ISSUE THREAD

**Issue by Keats** [chronotope/chrono-tz#9]
Would it make sense to try to add this crate in the https://github.com/chronotope organization?

**Comment by lifthrasiir** [comment]
@djzin For what it's worth, I've invited you to the chronotope org; please check the invitation. (I wanted to send an email for details but you didn't have any email address attached.)

**Comment by djzin** [comment]
Thanks @lifthrasiir - seems like a good idea to move this crate (and maybe the parse-zoneinfo crate it depends on)

**Comment by djzin** [comment]
I \*think\* it worked :)
