### ISSUE TITLE
Import of timezone fails

### ISSUE THREAD

**Issue by stanhebben** [chronotope/chrono-tz#98]
Attempting with a minimal example fails:

- I created an empty directory and ran `crate init`
- Added `chrono = "0.4.19"` and `chrono-tz = "0.6.1"` to `Cargo.toml` dependencies

Contents of main.rs:

```rust
extern crate chrono;
extern crate chrono_tz;

use chrono::TimeZone;
use chrono_tz::Europe::Brussels;

fn main() {
    let now = Brussels::now();
    println!("It's now {} in Brussels", now);
}
```

Attempting a `cargo run` or `cargo build` results in the following error:

```
error[E0433]: failed to resolve: use of undeclared type `Brussels`
 --> src\main.rs:8:15
  |
5 | use chrono_tz::Europe::Brussels;
  |     --------------------------- help: `Brussels` is defined here, but is not a type
...
8 |     let now = Brussels::now();
  |               ^^^^^^^^ use of undeclared type `Brussels`
```

Tested both with stable 1.59.0 and nightly 1.61.0.
Did I miss something or did this break in recent versions of Rust?

**Comment by djc** [comment]
I haven't checked, but I don't think this is a recent change. `Brussels` is an instance of type `Tz`, not a type, therefore you cannot call methods on it with `::`. You can instead call `TimeZone` and `Tz` methods on it with `.`, like `Brussels.name()`.

**Comment by stanhebben** [comment]
Apparently I'm the one confused indeed.

The following does work:

```
use chrono::{Duration, NaiveDate, NaiveTime, Utc, NaiveDateTime};
use chrono_tz::Europe::Brussels;

fn main() {
    let now = Utc::now().with_timezone(&Brussels).naive_local();
    println!("It's now {} in Brussels", now);
}
```

My confusion was due to Utc::now() working, but Utc *is* a type and not a timezone constant.
